### ISSUE TITLE
Change Images in Home Page

### ISSUE THREAD

**Issue by sirjan13** [sirjan13/CodeBizz#1]
Currently,the home page looks like this:
![image](https://user-images.githubusercontent.com/22820957/31057667-59e1fa08-a704-11e7-84c0-8cc6bebb9013.png)
The 4 images above the footer,need to be changed to Images of
1)Codechef,
2)hackerrank,
3)Spoj,
4)CodeForces 
and the heading needs to be changed to Editorials instead of New Articles.

**Comment by mdew192837** [comment]
I'll take this up

**Comment by sirjan13** [comment]
sure :)
