### ISSUE TITLE
Add Images In the Slider in index.html

### ISSUE THREAD

**Issue by sirjan13** [sirjan13/CodeBizz#5]
Currently the slider has 2 images, add 2 more images which are responsive The images should be realted to coding and programming like the other 2 are and should be of good quality.
NOTE: Include a screen shot of the new images in slider. The Text on every Image Would be CodeBizz as in the other 2 pictures.

**Comment by ghost** [comment]
#6 uploaded generic image to slider
![screenshot](https://user-images.githubusercontent.com/15345230/31081292-4f213726-a783-11e7-9eb1-f1770d3dc53b.jpg)

**Comment by NishantTanwar** [comment]
#7 added images to slider 
@sirjan13 please review 
screenshot->
![image](https://user-images.githubusercontent.com/21158671/31081080-46cb1eb4-a7a8-11e7-8ef1-57952c380801.png)

**Comment by sirjan13** [comment]
We wanted 2 images there so couldnt merge yours but would be great if you could raise an issue and give a pr for JUST this image . Thanks.Looking forward to more contributions
